#!/bin/sh

#### packages

sudo apt-get install screen git vim-gnome unison avahi-discover htop
# vim-gnome for vim server feature

#### bashrc

export PATH=$PATH:\bin

#### dotfiles

cd ~
git clone https://github.com/grirgz/dotfiles.git

ln -s ~/dotfiles/.vimrc ~/.vimrc

mkdir ~/.config/SuperCollider
ln -s ~/dotfiles/startup.scd ~/.config/SuperCollider/startup.scd

mkdir ~/bin
ln -s ~/dotfiles/seco ~/bin
ln -s ~/dotfiles/sound ~/bin
ln -s ~/dotfiles/nosound ~/bin
ln -s ~/dotfiles/update_repos ~/bin
ln -s ~/dotfiles/samples.prf ~/.unison/

#### vim

cd ~
git clone https://github.com/grirgz/vimrc.git ~/.vim

#### projects

mkdir -p ~/code/sc/
git clone https://github.com/grirgz/seco_live.git seco

#### Extensions

mkdir ~/.local/share/SuperCollider/Extensions
cd ~/.local/share/SuperCollider/Extensions
git clone https://github.com/grirgz/extensions.git seco

#### seco files

cd ~/.local/share/SuperCollider/Extensions/seco
git clone https://github.com/grirgz/seco.git seco

#### samples

mkdir -p ~/Musique/sc/samplekit
unison samples

#### quarks

wslib # isSymbolWS
jitlibextensions # Halo getSpec
