#!/bin/sh

CMD="git add . && git commit -a && git push"

echo BEGIN ========================= dotfiles

cd ~/dotfiles/
sh -c "$CMD"

echo ========================= seco classes

cd ~/.local/share/SuperCollider/Extensions/seco
sh -c "$CMD"

echo ========================= seco files

cd ~/.local/share/SuperCollider/Extensions/seco/seco
sh -c "$CMD"

echo ========================= projects

cd ~/code/sc/seco
sh -c "$CMD"

echo ========================= vim

cd ~/.vim
sh -c "$CMD"

echo ========================= END
