#!/bin/sh

CMD="git pull"

cd ~/dotfiles/
sh -c "$CMD"

cd ~/.vim/
sh -c "$CMD"

cd ~/code/sc/seco/
sh -c "$CMD"

cd ~/code/sc/seco/vlive/cuspn
sh -c "$CMD"

cd ~/.local/share/SuperCollider/Extensions/seco
sh -c "$CMD"

cd ~/.local/share/SuperCollider/Extensions/seco/seco
sh -c "$CMD"
